# See https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/github-actions.md#trigger-semantic-release-on-demand

name: Publish using semantic-release
on:
  repository_dispatch:
    types: [semantic-release]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.npm_token }}
        run: npx semantic-release
